### PR TITLE
Initialize swagger checker from swagger object directly

### PR DESCRIPTION
**Pull request by ben-axnick**
Intended to address: https://github.com/westfieldlabs/apivore/issues/100

## Background

Currently the `SwaggerChecker` initialize method has no flexibility about how `Apivore::Swagger` is constructed. By accepting a full object, the client gains the flexibility to fetch a swagger file however it wishes to, whether by file, remote HTTPS, or carrier pigeon.

Since README and specs revolve around `.instance_for`, whose signature remains unchanged, there are no other changes required.

## What have I done?

- The previous initialization routine has been moved to `.from_local_route`, and `.instance_for` has been updated to reflect that.
- The new initializer accepts a `Apivore::Swagger` (or any object that accepts `#validate` and `#each_response`)

### CODE REVIEW

**Comment by ben-axnick** [comment]
Closing because I don't want to see this in my PR list forever.

If you're interested in merging down the line, I'm happy to help make any changes you feel need to be made.

**Comment by philsturgeon** [comment]
Wish I saw this before making #118. If there is interest from the maintainers about that PR I'll pull this in and tweak it a little. I'm unhappy with the two-different places to check if JSON/YAML.

**Comment by ben-axnick** [comment]
Yeah, I had closed owing to the fact that it seemed like PRs weren't being handled or looked into at all by the maintainers, hopefully your PR meets with greater success.

**Comment by philsturgeon** [comment]
Thank you, but I just leave mine floating around like dingleberries!

**Pull request closed without merging**
