### PR TITLE
Add apivore integration tests to verify negative use cases

### PR DESCRIPTION
**Pull request by hornc**
@leondewey , @benpritchard 
*UPDATE:* I've added more tests and refactored based on comments. I think this is ready to merge.
The current behaviour is to pass if there are extra (undocumented) fields in the API response, I've added a test to confirm that behaviour. There is also a pending test to verify the opposite for when we add an option to use strict validation. A possible issue with this 'strict' mode is that it also assumes all properties are required, which I don't think we want. We may need to create a custom validation that fails on extra properties, but allows explicitly declared optional properties to be present, or not.

---
This is my attempt at adding some tests to check apivore will fail when a description and API do not match up.

I'm using a simplified version of the approach used by rspec to test rspec using rspec. This runs rspec as a system command rather than calling the rspec runner again (to avoid conflicts by running nested tests in the same env).

I feel there is a bit of duplication and the test set-up could be neater, so I'm putting this up as a WIP for comment while I think on a way to make it neater. I've gone for getting the basic tests working in the first place, and then I'll tidy up, then add the remainder of the scenarios I have identified.

Some of the text expectations are too coupled to rspec for my liking too.

I'd like a way to avoid having many copies of the same swagger file with only minor modifications to set up the scenarios. I was thinking of just altering the json programatically as needed, but I'm not sure where to do this. It'd be easiest from within the spec/fixtures/application.rb file, but I think it'd be neater if the expected json response could be set in the spec file with the particular test.

@benpritchard @leondewey , I'd appreciate any comments you have on this PR. Feel free to get in touch if you need more context, it took me multiple goes to find an approach that even worked at all, so it's probably difficult to get at first glance.

Cheers,
Charles.

### CODE REVIEW

**Comment by hornc** [comment]
The purpose of this is to test that apivore will fail on the desired scenarios -- the feedback I've got is that there has been some confusion of what to expect around the 'strictness' of validations, and on the helpfulness of pinpointing a problem with the swagger. I'd like these tests to be able to test for helpful output for each kind of scenario and provide clear examples on what kinds of errors are caught and which are not.

I think the consensus is that undocumented fields in a response should _not_ cause a failure? Either way, I want tests in place so it can't change without anyone noticing.

**Comment by leondewey** [comment]
I think undocumented fields should fail... Think the idea is that you can add a field to a version with out having to bump the number.

**Comment by leondewey** [comment]
So you are testing the JSON validator does what we expect and returns a good message?

**Comment by hornc** [comment]
@leondewey That's correct, that's what I'm trying to do with this. There seemed to be some confusion from the devs, and we've had a few issues with false positives (i.e. everything goes green when there is an issue with the swagger) I want to make sure that sort of thing can't happen.

**Pull request merged**
