### PR TITLE
Fix testing the same path multiple times

### PR DESCRIPTION
**Pull request by gingermusketeer**

### CODE REVIEW

**Comment by gingermusketeer** [comment]
The json validator is mutating the fragment being passed in so we need to duplicate our fragment before validation

**Comment by ashoda** [comment]
LGTM

**Comment by hornc** [comment]
Interesting, I didn't realise it was doing that. Good find :+1:

**Comment by danielocallaghan** [comment]
@hornc twas' stumbled upon, cheers will retest

**Pull request merged**
